### ISSUE TITLE
Bug/Issue

### ISSUE THREAD

**Issue by MishSilkov** [Fresh791/Fading-Revelations#56]
я не могу вылезти из основного ядра при нажатии кнопки V я снова спавнюсь в ядре
![image](https://github.com/Fresh791/Fading-Revelations/assets/121912736/86a4c51d-9021-4df9-b682-9a44c8df3232)
![image](https://github.com/Fresh791/Fading-Revelations/assets/121912736/8f1d4c86-b0e0-40f8-bec8-5e20679aed60)
![image](https://github.com/Fresh791/Fading-Revelations/assets/121912736/f682c560-18ef-4c0a-9d47-706970c48133)

**Comment by MishSilkov** [comment]
> Намеренно. Основное ядро позволяет вам управлять самим ядром, а не конкретным устройством.

а как мне выйти из него обратно заспавнить юнитом как это делает обычное ядро? или мне нужно обьязательно два ядра чтобы играть я не понимаю основное ядро не может быть использовано как основное?

**Comment by overdramaticpanromantic** [comment]
To get into a regular unit, CTRL+Click another unit. You can do this with a "Mega", "Poly", or otherwise.

**Comment by overdramaticpanromantic** [comment]
The functionality is odd, unfortunately.

**Comment by overdramaticpanromantic** [comment]
(You can also use SHIFT+WASD to move your camera.)
